---
- hosts: all
  become: yes

  tasks:

    - name: create docker image using war file
      command: docker build -t simple-devops-image:latest .
      args:
        chdir: /opt/docker

    - name: create tag to image
      command: docker tag simple-devops-image chaitumandepu/simple-devops-image

    - name: push image on to dockerhub
      command: docker push chaitumandepu/simple-devops-image

    - name: remove docker images from ansible server
      command: docker rmi -f tomcat simple-devops-image:latest chaitumandepu/simple-devops-image
      ignore_errors: yes
